#!/bin/sh

if [ -n "${MAINTENANCE_PAGE_URL}" ]; then
  wget $MAINTENANCE_PAGE_URL -O /usr/share/nginx/html/50x.html 2>/dev/null
  sed -i \
    's/http {$/http {\n  error_page 502 503 504 \/50x.html;/' \
    /etc/nginx/nginx.conf
fi

/usr/sbin/nginx $@
